export type SystemId = 'digestive'|'respiratory'|'circulatory'|'nervous'|'muscular'|'skeletal'|'urinary';
export type Step = {name:string; organ:string; simple:string; advanced:string; tag:string};
export type BodySystem = {id:SystemId;name:string;subtitle:string;color:string;intro:string;process:string;steps:Step[];organs:string[];fact:string;source:{title:string;url:string}[]};
const step=(name:string,organ:string,simple:string,advanced:string,tag:string):Step=>({name,organ,simple,advanced,tag});
export const systems:BodySystem[]=[
{id:'digestive',name:'Digestive',subtitle:'Nourish & absorb',color:'#d88243',intro:'Follow a bite of food as your body turns it into the nutrients that power you.',process:'The journey of a bite',organs:['Mouth','Teeth & tongue','Salivary glands','Pharynx','Esophagus','Stomach','Liver','Gallbladder','Pancreas','Small intestine','Large intestine','Rectum','Anus'],fact:'Food travels through the gut. The liver, gallbladder and pancreas help by releasing digestive fluids into it.',source:[{title:'NIDDK · Your digestive system',url:'https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works'},{title:'OpenStax · Digestion and absorption',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/23-2-digestive-system-processes-and-regulation'}],steps:[
step('Take a bite','Mouth','Food enters your mouth, where digestion begins.','Ingestion brings food into the oral cavity. Sight, smell and taste can stimulate digestive secretions before swallowing.','Ingestion'),
step('Chew & shape','Teeth & tongue','Teeth break food into smaller pieces. Your tongue mixes it and shapes a soft ball called a bolus.','Mastication increases the surface area available to enzymes. The tongue positions food between the teeth and forms the bolus for swallowing.','Mechanical digestion'),
step('Mix with saliva','Salivary glands','Saliva moistens your food and starts breaking down starch.','Salivary amylase begins starch hydrolysis. Mucus lubricates the bolus. Salivary glands release fluid into the mouth; food does not travel through them.','Chemical digestion'),
step('Swallow safely','Pharynx','Your tongue pushes food into your throat. The airway closes briefly to help keep food out of your lungs.','During the pharyngeal phase of swallowing, the soft palate closes the nasopharynx and laryngeal elevation and epiglottic movement protect the airway.','Swallowing'),
step('Move down','Esophagus','Waves of squeezing muscles push the bolus down to your stomach.','Coordinated peristalsis propels the bolus. The lower esophageal sphincter relaxes for entry into the stomach, then helps prevent reflux.','Peristalsis'),
step('Churn & break down','Stomach','Your stomach mixes food with acid and enzymes, turning it into a thick liquid called chyme.','Hydrochloric acid denatures proteins and supports pepsin activity. Gastric mixing disperses food, while the pyloric sphincter meters chyme into the duodenum.','Mixing'),
step('Digest & absorb','Small intestine','Digestive juices finish breaking down food. Tiny folds and villi help nutrients enter blood or lymph.','Pancreatic enzymes and brush-border enzymes complete digestion; bile emulsifies fats. Sugars and amino acids enter capillaries. Most long-chain fats leave via lymphatic lacteals.','Nutrient absorption'),
step('Reclaim water','Large intestine','The colon absorbs more water and salts. Bacteria process some leftovers, and waste becomes stool.','The colon absorbs remaining water and electrolytes. Microbial fermentation produces short-chain fatty acids. Mass movements propel fecal material toward the rectum.','Water absorption'),
step('Store the waste','Rectum','Stool waits in the rectum until your body is ready to release it.','Rectal stretch activates the defecation reflex. The internal anal sphincter relaxes while voluntary control of the external sphincter can delay release.','Storage'),
step('Complete the journey','Anus','Sphincter muscles relax to allow stool to leave the body.','Coordinated rectal contractions, pelvic-floor relaxation and external anal sphincter control permit defecation. This eliminates unabsorbed material, microbes and shed cells.','Elimination')
]},
{id:'respiratory',name:'Respiratory',subtitle:'Breathe & exchange',color:'#548fb1',intro:'Trace a breath from the air around you to the tiny air sacs inside your lungs.',process:'One breath, inside out',organs:['Nose & mouth','Trachea','Bronchi','Lungs','Alveoli','Diaphragm'],fact:'Oxygen and carbon dioxide cross the thin alveolar barrier in opposite directions by diffusion.',source:[{title:'NHLBI · Airways and lungs',url:'https://www.nhlbi.nih.gov/health/lungs/respiratory-system'},{title:'NHLBI · Breathing',url:'https://www.nhlbi.nih.gov/health/lungs/breathing-benefits'}],steps:[
step('Draw air in','Nose & mouth','Your diaphragm contracts downward. The chest expands and air enters through your nose or mouth.','Expansion lowers alveolar pressure below atmospheric pressure. Nasal passages warm, humidify and filter inspired air before it passes through the pharynx and larynx.','Inhalation'),
step('Follow the windpipe','Trachea','Air travels down the trachea, a tube held open by rings of cartilage.','C-shaped cartilage supports the trachea. Mucus traps particles and cilia move debris toward the pharynx. The esophagus behind it carries food separately.','Air transport'),
step('Branch into the lungs','Bronchi','Two main bronchi divide into smaller bronchioles, spreading air through the lungs.','The right main bronchus is more vertical. Repeated branching conducts air to respiratory bronchioles, alveolar ducts and alveolar sacs.','Distribution'),
step('Fill the air sacs','Lungs','The lungs expand as fresh air reaches clusters of tiny air sacs called alveoli.','The right lung has three lobes and the left has two. Surfactant reduces alveolar surface tension; the pleural linkage transmits chest-wall movement to the lungs.','Ventilation'),
step('Exchange gases','Alveoli','Oxygen moves from the air sacs into blood. Carbon dioxide moves from blood into the air sacs.','Partial-pressure gradients drive diffusion across the alveolar–capillary barrier. Oxygen binds to hemoglobin, while carbon dioxide diffuses into alveolar air to be exhaled.','Gas exchange'),
step('Breathe out','Diaphragm','The diaphragm relaxes. Elastic recoil pushes air carrying carbon dioxide back out through the airways.','Quiet expiration is mainly passive. Lung and chest-wall recoil raise alveolar pressure above atmospheric pressure, reversing airflow through bronchi, trachea and nose or mouth.','Exhalation')
]},
{id:'circulatory',name:'Circulatory',subtitle:'Pump & transport',color:'#c5616b',intro:'Follow blood through the heart, to the lungs and around the body in one continuous circuit.',process:'A complete circulation',organs:['Heart','Right atrium','Tricuspid valve','Right ventricle','Pulmonary valve','Pulmonary arteries','Lungs','Pulmonary veins','Left atrium','Mitral valve','Left ventricle','Aortic valve','Arteries','Veins'],fact:'Arteries carry blood away from the heart; veins return it. Blue represents lower oxygen here—human blood is always red.',source:[{title:'NHLBI · Blood flow and valves',url:'https://www.nhlbi.nih.gov/health/heart/blood-flow'},{title:'NHLBI · Heart anatomy',url:'https://www.nhlbi.nih.gov/health/heart/anatomy'}],steps:[
step('Return to the heart','Right atrium','Oxygen-poor blood returns from the body through the venae cavae and fills the right atrium.','Systemic veins converge into the superior and inferior vena cava. The right atrium also receives venous return from the myocardium via the coronary sinus.','Venous return'),
step('Enter the right ventricle','Tricuspid valve','Blood passes through the tricuspid valve into the right ventricle.','During ventricular filling, the right atrioventricular valve is open. Rising ventricular pressure closes it; chordae tendineae help prevent leaflet prolapse.','One-way valve'),
step('Pump toward the lungs','Right ventricle','The right ventricle contracts, pushing blood through the pulmonary valve into the pulmonary arteries.','The pulmonary valve opens when right ventricular pressure exceeds pulmonary arterial pressure. The pulmonary arteries carry oxygen-poor blood to lung capillaries.','Pulmonary circulation'),
step('Pick up oxygen','Lungs','In the lung capillaries, blood releases carbon dioxide and takes up oxygen.','Gas diffusion is driven by partial-pressure gradients. Oxygenated blood returns through the pulmonary veins, unlike the oxygen-poor blood in most systemic veins.','Gas exchange'),
step('Fill the left side','Left atrium','Pulmonary veins bring oxygen-rich blood into the left atrium. It passes through the mitral valve.','The mitral valve lies between the left atrium and ventricle. During diastole, most ventricular filling is passive, with atrial contraction contributing additional volume.','Heart filling'),
step('Power the body','Left ventricle','The left ventricle pumps blood through the aortic valve into the aorta and its branches.','The muscular left ventricular wall generates systemic pressure. The aortic valve prevents backflow during relaxation; coronary arteries supply the heart muscle itself.','Systemic circulation'),
step('Deliver & return','Arteries','Small blood vessels deliver oxygen and nutrients to tissues. Blood then returns through veins.','Arteries branch into arterioles and capillaries. Exchange occurs across capillary walls; venules collect the blood and systemic veins return it to the right atrium.','Tissue exchange')
]},
{id:'nervous',name:'Nervous',subtitle:'Sense & respond',color:'#b59a46',intro:'See how a touch becomes a signal, a sensation and a coordinated response.',process:'From sensation to action',organs:['Brain','Spinal cord','Sensory nerves','Motor nerves'],fact:'Some protective reflexes are coordinated in the spinal cord before you consciously recognize the stimulus.',source:[{title:'NINDS · Know your brain',url:'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-know-your-brain'},{title:'OpenStax · The nervous system',url:'https://openstax.org/books/anatomy-and-physiology/pages/14-introduction'}],steps:[
step('Detect a touch','Sensory nerves','Receptors in your hand detect a touch and trigger nerve signals.','Mechanoreceptors convert deformation into changes in membrane potential. If threshold is reached, sensory neurons generate action potentials.','Sensory input'),
step('Travel inward','Spinal cord','Sensory signals travel along peripheral nerves to the spinal cord and toward the brain.','Afferent fibers enter via dorsal roots. Ascending pathways relay information; local interneurons can also coordinate a spinal reflex.','Afferent pathway'),
step('Make sense of it','Brain','Your brain interprets the signal and plans a response, such as moving your hand.','Thalamic and cortical networks process most body sensations. Motor areas plan and initiate voluntary movement, while the cerebellum helps coordinate it.','Integration'),
step('Send a command','Motor nerves','A motor command travels down the spinal cord and out through nerves to the muscles.','Descending pathways influence lower motor neurons. Their axons exit through ventral roots and release acetylcholine at neuromuscular junctions.','Efferent pathway'),
step('Move & adjust','Motor nerves','Muscles respond. Sensory feedback tells the brain how the movement is going.','Proprioceptors monitor muscle length and tension. Feedback allows rapid corrections; signals are electrical along axons and usually chemical across synapses.','Response & feedback')
]},
{id:'muscular',name:'Muscular',subtitle:'Contract & move',color:'#ad6660',intro:'Explore how a nerve signal becomes muscle tension and movement at a joint.',process:'The making of a movement',organs:['Deltoids','Pectorals','Biceps','Triceps','Forearm muscles','Abdominals','Quadriceps','Calves','Trapezius','Latissimus dorsi','Gluteals','Hamstrings','Tibialis anterior'],fact:'Muscles pull on bones through tendons. Opposing muscle groups help move a joint in both directions.',source:[{title:'OpenStax · Skeletal muscle',url:'https://openstax.org/books/anatomy-and-physiology/pages/10-2-skeletal-muscle'}],steps:[
step('Receive the command','Biceps','A motor nerve tells muscle fibers to prepare to contract.','Acetylcholine at the neuromuscular junction depolarizes the muscle-fiber membrane. An action potential spreads along the sarcolemma and T tubules.','Activation'),
step('Unlock the fibers','Biceps','Calcium inside the muscle allows tiny protein filaments to work together.','Calcium is released from the sarcoplasmic reticulum and binds troponin. Tropomyosin shifts, exposing myosin-binding sites on actin.','Calcium release'),
step('Pull & shorten','Biceps','Myosin pulls on actin. The muscle shortens and bends the elbow.','ATP-dependent cross-bridge cycling slides thin filaments past thick filaments, shortening sarcomeres. The filaments themselves do not shorten.','Contraction'),
step('Relax & return','Triceps','The biceps relaxes. The triceps can contract to straighten the elbow again.','Calcium is pumped back into the sarcoplasmic reticulum. Antagonistic muscles and external forces lengthen the relaxed muscle and reverse movement.','Relaxation')
]},
{id:'skeletal',name:'Skeletal',subtitle:'Support & protect',color:'#9b927c',intro:'Discover the framework that protects your organs and turns muscle forces into movement.',process:'How a joint moves',organs:['Skull','Rib cage','Spine','Pelvis','Humerus','Radius & ulna','Femur','Tibia & fibula','Hand bones','Foot bones'],fact:'Bone is living tissue: it supports movement, stores minerals and contains marrow that produces blood cells.',source:[{title:'OpenStax · Bone and skeletal tissue',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/6-introduction'}],steps:[
step('Support the body','Spine','Your skeleton provides a strong framework for the body and protects important organs.','The axial skeleton includes the skull, vertebral column and thoracic cage. The appendicular skeleton comprises the limbs and their girdles.','Support'),
step('Apply a force','Humerus','A contracting muscle pulls a tendon attached to a bone.','Bones act as levers and joints act as fulcrums. Tendons connect muscles to bones; ligaments help stabilize connections between bones.','Leverage'),
step('Move at the joint','Radius & ulna','Your forearm rotates around the elbow joint, allowing your hand to move.','In flexion and extension, the humeroulnar articulation acts mainly as a hinge. Articular cartilage and synovial fluid reduce friction.','Articulation'),
step('Adapt & renew','Femur','Bones continually renew themselves and adapt to the forces placed on them.','Osteoclasts resorb bone and osteoblasts form new matrix. Remodeling supports mechanical strength and calcium balance; red marrow produces blood cells.','Remodeling')
]},
{id:'urinary',name:'Urinary',subtitle:'Filter & balance',color:'#8c7db8',intro:'Follow how the kidneys filter blood, keep what you need and remove waste as urine.',process:'From blood to urine',organs:['Kidneys','Ureters','Bladder','Urethra'],fact:'Kidneys filter blood, not food. Most filtered water returns to the bloodstream before the remaining fluid becomes urine.',source:[{title:'NIDDK · Your kidneys',url:'https://www.niddk.nih.gov/health-information/kidney-disease/kidneys-how-they-work'}],steps:[
step('Filter the blood','Kidneys','Blood reaches your kidneys. Tiny filters let water and small molecules enter the kidney tubules.','Glomerular pressure drives filtration into Bowman’s capsule. Blood cells and most proteins remain in the circulation rather than entering healthy filtrate.','Filtration'),
step('Keep what you need','Kidneys','Tubules return useful substances and most water to the blood, while adding some wastes to the fluid.','Tubular reabsorption recovers glucose, electrolytes and water; secretion transfers selected ions and organic compounds from blood to tubular fluid.','Reabsorption & secretion'),
step('Travel to the bladder','Ureters','Urine drains through the renal pelvis and travels down two ureters.','Smooth-muscle peristalsis propels urine through each ureter. The oblique entry into the bladder helps limit reflux as the bladder fills.','Urine transport'),
step('Store the urine','Bladder','The bladder stretches as it fills, holding urine until you are ready.','The detrusor muscle relaxes during storage while urethral sphincters help maintain continence. Stretch receptors signal increasing bladder volume.','Storage'),
step('Release & rebalance','Urethra','The bladder contracts and sphincters relax. Urine exits through the urethra.','Micturition coordinates detrusor contraction with outlet relaxation. Urethral anatomy varies by sex; the model uses a shortened schematic outlet.','Urination')
]}
];
export const getSystem=(id:SystemId)=>systems.find(s=>s.id===id)!;
export const organNotes:Record<string,[string,string]>={
'Heart':['The heart is a muscular pump with four chambers. Its right side sends blood to the lungs; its left side sends oxygen-rich blood around the body. Valves keep blood moving forward.','The right and left atria receive venous return, while the ventricles eject blood into the pulmonary and systemic circuits. Pressure differences drive blood through four valves. Myocardial contraction and relaxation alternate as systole and diastole; the animation illustrates motion rather than a measured cardiac cycle.'],
'Liver':['Makes bile to help digest fats, processes absorbed nutrients and performs many metabolic tasks.','Hepatocytes produce bile and process portal venous nutrients. Bile reaches the duodenum through the biliary tree; food does not enter the liver.'],
'Gallbladder':['Stores and concentrates bile, then releases it into the small intestine.','Cholecystokinin promotes gallbladder contraction and bile delivery to the duodenum. Bile salts emulsify fats and help form micelles.'],
'Pancreas':['Sends digestive enzymes and bicarbonate into the small intestine.','Exocrine acinar cells secrete enzymes; duct cells supply bicarbonate to help neutralize gastric acid. Endocrine islets separately release insulin and glucagon into blood.'],
'Pulmonary valve':['Opens for blood to leave the right ventricle toward the lungs.','This semilunar valve opens when right ventricular pressure exceeds pulmonary arterial pressure and closes when the pressure gradient reverses.'],
'Pulmonary arteries':['Carry oxygen-poor blood from the right ventricle to the lungs.','The pulmonary trunk divides into right and left pulmonary arteries. Artery means away from the heart, regardless of oxygen content.'],
'Pulmonary veins':['Return oxygen-rich blood from the lungs to the left atrium.','Usually four pulmonary veins return oxygenated blood. Vein means toward the heart, regardless of oxygen content.'],
'Mitral valve':['A one-way gate between the left atrium and left ventricle.','The two leaflets close as ventricular pressure rises. Chordae tendineae and papillary muscles help prevent prolapse during systole.'],
'Aortic valve':['Lets blood leave the left ventricle and helps prevent it flowing backward.','The aortic semilunar valve opens during ventricular ejection and closes when aortic pressure exceeds left ventricular pressure.'],
'Tricuspid valve':['Lets blood flow from the right atrium into the right ventricle.','The right atrioventricular valve opens during filling and closes when right ventricular pressure rises. Its leaflets are supported by chordae tendineae.'],
'Veins':['Return blood to the heart. Many limb veins have valves that help prevent backflow.','Venous return is supported by pressure gradients, skeletal muscle contraction and respiratory pressure changes.'],
'Skull':['Protects the brain and supports the face.','Cranial bones surround the brain; facial bones form the orbits, nasal cavities and jaws. Most skull bones meet at immovable sutures.'],
'Rib cage':['Protects the heart and lungs while allowing the chest to expand for breathing.','Twelve pairs of ribs articulate with thoracic vertebrae. Costal cartilages connect ribs to the sternum directly or indirectly, except the floating ribs.'],
'Pelvis':['Transfers weight to the legs and protects organs in the pelvic cavity.','The two hip bones articulate with the sacrum at the sacroiliac joints. Each acetabulum receives the head of a femur.'],
'Tibia & fibula':['Two bones form the lower leg; the tibia carries most of its weight.','The medial tibia transmits load between knee and ankle. The lateral fibula provides muscle attachments and supports ankle stability.'],
'Forearm muscles':['Move the wrist and fingers, supporting grip and fine hand movements.','Flexor and extensor compartments act across the wrist and finger joints. Multiple muscles also contribute to pronation and supination of the forearm.'],
'Hand bones':['Support the palm and fingers for grasping and precise movement.','The hand contains carpal bones, metacarpals and phalanges. Joint shape and muscle attachments allow both stability and fine control.'],
'Foot bones':['Support body weight and help you balance and push off when walking.','Tarsals, metatarsals and phalanges form the foot. Longitudinal and transverse arches distribute load and absorb forces.'],
'Deltoids':['Lift the arm at the shoulder.','Anterior, middle and posterior fibers contribute to flexion, abduction and extension of the shoulder respectively.'],
'Pectorals':['Pull the upper arm inward and help move it forward.','Pectoralis major adducts and medially rotates the humerus. Its clavicular fibers contribute to shoulder flexion.'],
'Abdominals':['Support the trunk, bend the spine and help regulate abdominal pressure.','Rectus abdominis flexes the trunk; obliques rotate and laterally flex it; transversus abdominis compresses the abdominal contents.'],
'Quadriceps':['Straighten the knee and stabilize the leg.','The four quadriceps muscles insert through the quadriceps tendon, patella and patellar ligament to the tibial tuberosity.'],
'Trapezius':['Moves and supports the shoulder blades.','Upper, middle and lower portions coordinate elevation, retraction and rotation of the scapula.'],
'Latissimus dorsi':['Pulls the upper arm down and back.','The broad back muscle extends, adducts and medially rotates the humerus.'],
'Gluteals':['Move and stabilize your hips when standing and walking.','Gluteus maximus extends the hip; gluteus medius and minimus help abduct the hip and stabilize the pelvis.'],
'Hamstrings':['Bend the knee and help move the thigh backward.','Biceps femoris, semitendinosus and semimembranosus flex the knee; most also extend the hip.'],
'Tibialis anterior':['Raises the front of the foot.','This anterior leg muscle dorsiflexes and inverts the foot at the ankle.'],
'Calves':['Push the foot down to help you walk, run and stand on tiptoe.','Gastrocnemius and soleus plantarflex the ankle via the Achilles tendon. Gastrocnemius also contributes to knee flexion.']
};
export function describeOrgan(s:BodySystem,name:string,advanced:boolean){const pair=organNotes[name];if(pair)return pair[advanced?1:0];const found=s.steps.find(t=>t.organ===name);return found?(advanced?found.advanced:found.simple):s.intro;}
